### ISSUE TITLE
When did you create X_train_scaled_jaffe.npy and Y_train_scaled_jaffe.npy?

### ISSUE THREAD

**Issue by pmarkous** [cprinzz/emotion-classifier#2]
When did you create X_train_scaled_jaffe.npy and Y_train_scaled_jaffe.npy?
You are calling:
X_train_test = np.load(X_train_fname)
Y_train_test = np.load(Y_train_fname)
But i can't see when they where created.
Thank you for sharing this! Its very interesting

**Comment by cprinzz** [comment]
https://github.com/cprinzz/emotion-classifier/blob/master/notebooks/CreateTrainTestCV.ipynb

I create the training sets in one of the bottom cells in this notebook. It took me a second to find, it's been a while since I built this 😅

I'll add it to the readme.

**Comment by pmarkous** [comment]
sorry to ask again, i see on "Convert to categorical arrays, and save to file" that you create:
np.save('../data/X_train_scaled_jaffe_ck_dlib', X_train)
np.save('../data/Y_train_scaled_jaffe_ck_dlib', Y_train)
np.save('../data/X_test_scaled_jaffe_ck_dlib', X_test)
np.save('../data/Y_test_scaled_jaffe_ck_dlib', Y_test)

But then you load:
X_train_fname = '../data/X_train_scaled_jaffe.npy'
Y_train_fname = '../data/Y_train_scaled_jaffe.npy'
X_train_test = np.load(X_train_fname)
Y_train_test = np.load(Y_train_fname)

those Y_train_scaled_jaffe.npy and Y_train_scaled jaffe.npy don't know when where created

**Comment by cprinzz** [comment]
I think at some point I started experimenting with scaling the images so that I could use a larger convolutional layer, and thus add more layers. So I think I would just change some params in the notebook and rename the file output. It's probably safe to rename those files to "X_train_scaled_jaffe"
